import * as THREE from 'three';
import {OrbitControls} from './vendor/OrbitControls.js';
import {FontLoader} from './vendor/FontLoader.js';
import {TextGeometry} from './vendor/TextGeometry.js';
const $=id=>document.getElementById(id);
const palette=[['Black','#131313'],['White','#ffffff'],['Cream','#f3d8a5'],['Baby Blue','#80c8ec'],['Blue','#2862ed'],['Olive Green','#7d913e'],['Forest Green','#096b40'],['Red','#f70835'],['Orange','#ff861b'],['Sakura Pink','#f396b8'],['Violet Purple','#d413b7'],['Grey','#c3c5c7'],['Dark Grey','#616367'],['Yellow','#fff02e'],['Chocolate','#905b32'],['Silver','#d6dade']];
const state={name:'',model:'classic',base:9,keycaps:13,text:9};let part='base',scene,camera,renderer,controls,model,font,raf=0,fitDistance=10,modelWidth=7,frameTimer=0,visible=true,rendering=false,materials={},capGeometry,letterCache=new Map(),baseTemplate,flexJoints=[],flexParts=[],heartGeometry,squareGeometry,cookieGeometry,wavePose=[],waveStopAt=null,flexDemoStart=0,flexAngles={yaw:0,pitch:0};let ready=false,initializing;const modelColors={classic:{base:9,keycaps:13,text:9},'heart-flex':{base:1,keycaps:7,text:1},'square-flex':{base:1,keycaps:9,text:1},'cookie-flex':{base:14,keycaps:2,text:14},wafer:{base:14,keycaps:2,text:14},curved:{base:4,keycaps:1,text:4},heart:{base:7,keycaps:1,text:7},flower:{base:8,keycaps:1,text:8}};
function toast(msg){$('toast').textContent=msg;$('toast').classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('toast').classList.remove('show'),3200)}
function renderPalette(){document.querySelectorAll('[data-part]').forEach(b=>{const active=b.dataset.part===part;b.classList.toggle('active',active);b.setAttribute('aria-selected',active);b.tabIndex=active?0:-1});$('colors').setAttribute('aria-labelledby','tab-'+part);$('partLabel').textContent='Warna '+({base:'base',keycaps:'keycaps',text:'teks'})[part];$('selectedLabel').textContent=palette[state[part]][0];$('colors').replaceChildren(...palette.map(([name,color],i)=>{const b=document.createElement('button');b.className='swatch';b.setAttribute('aria-label',name);b.setAttribute('aria-pressed',state[part]===i);b.style.setProperty('--color',color);const d=document.createElement('span');d.className='color-dot';d.style.color=[0,4,5,6,7,10,12,14].includes(i)?'#fff':'#352b26';d.textContent=state[part]===i?'✓':'';const t=document.createElement('span');t.className='color-name';t.textContent=name;b.append(d,t);b.onclick=()=>{state[part]=i;renderPalette();updateInfo();if(ready)updateMaterials()};return b}))}
function updateInfo(){updateFlexControls();$('count').textContent=state.name.length+' / 12';$('designName').textContent=state.name||'TANPA HURUF';$('summary').replaceChildren(...['base','keycaps','text'].map(k=>{const s=document.createElement('span'),i=document.createElement('i');i.style.background=palette[state[k]][1];s.append(i,document.createTextNode(palette[state[k]][0]));return s}))}
function setName(value){state.name=value.toUpperCase().replace(/[^A-Z0-9]/g,'').slice(0,12);$('name').value=state.name;updateInfo();if(ready)buildModel(true)}
$('name').addEventListener('input',e=>setName(e.target.value));
document.querySelectorAll('[data-part]').forEach((b,index)=>{b.onclick=()=>{part=b.dataset.part;renderPalette()};b.onkeydown=e=>{if(['ArrowLeft','ArrowRight','Home','End'].includes(e.key)){e.preventDefault();const tabs=[...document.querySelectorAll('[data-part]')];let n=e.key==='Home'?0:e.key==='End'?2:(index+(e.key==='ArrowRight'?1:2))%3;tabs[n].click();tabs[n].focus()}}});
renderPalette();updateInfo();
function roundedShape(w,h,r){const s=new THREE.Shape(),x=-w/2,y=-h/2;s.moveTo(x+r,y);s.lineTo(x+w-r,y);s.quadraticCurveTo(x+w,y,x+w,y+r);s.lineTo(x+w,y+h-r);s.quadraticCurveTo(x+w,y+h,x+w-r,y+h);s.lineTo(x+r,y+h);s.quadraticCurveTo(x,y+h,x,y+h-r);s.lineTo(x,y+r);s.quadraticCurveTo(x,y,x+r,y);return s}
function block(w,d,h,r,mat,bevel=.02){const geo=new THREE.ExtrudeGeometry(roundedShape(w-2*bevel,d-2*bevel,r),{depth:h-2*bevel,bevelEnabled:true,bevelSegments:2,steps:1,bevelSize:bevel,bevelThickness:bevel,curveSegments:4});geo.rotateX(-Math.PI/2);geo.translate(0,bevel,0);return new THREE.Mesh(geo,mat)}
function material(hex,metal=false){return new THREE.MeshPhongMaterial({color:hex,specular:metal?'#ffffff':'#353535',shininess:metal?85:24})}
function clearModel(){if(!model)return;scene.remove(model);const geometries=new Set();model.traverse(o=>{if(o.geometry&&!o.userData.shared)geometries.add(o.geometry)});geometries.forEach(g=>g.dispose())}
function updateMaterials(){for(const k of ['base','keycaps','text'])materials[k].color.set(palette[state[k]][1]);invalidate()}
function keycapGeometry(){const g=new THREE.ExtrudeGeometry(roundedShape(.92,.94,.065),{depth:.46,bevelEnabled:true,bevelSegments:2,bevelThickness:.018,bevelSize:.018,curveSegments:4,steps:1});const p=g.attributes.position;for(let i=0;i<p.count;i++){const h=p.getZ(i),scale=1-.19*Math.max(0,Math.min(1,h/.46));p.setXYZ(i,p.getX(i)*scale,p.getY(i)*scale,h)}g.rotateX(-Math.PI/2);g.computeVertexNormals();return g}
function glyphGeometry(char){if(letterCache.has(char))return letterCache.get(char);const geo=new TextGeometry(char,{font,size:.57,depth:.037,curveSegments:4,bevelEnabled:true,bevelThickness:.003,bevelSize:.003,bevelSegments:1});geo.computeBoundingBox();const box=geo.boundingBox;geo.translate(-(box.max.x+box.min.x)/2,-(box.max.y+box.min.y)/2,0);const scale=Math.min(.56/(box.max.y-box.min.y),.65/(box.max.x-box.min.x));geo.scale(scale,scale,1);geo.rotateX(-Math.PI/2);letterCache.set(char,geo);return geo}
function buildModel(fit){stopFlexDemo();clearModel();model=new THREE.Group();flexJoints=[];flexParts=[];const n=Math.max(state.name.length,1),width=n*1.025+.18;modelWidth=width+2.8;
if(!materials.base){materials={base:material(palette[state.base][1]),keycaps:material(palette[state.keycaps][1]),text:material(palette[state.text][1]),metal:material('#bfc2c5',true)};capGeometry=keycapGeometry()}
updateMaterials();
if(['heart','flower'].includes(state.model)){buildDecorative(n);finishModel(fit);return}
if(['wafer','curved'].includes(state.model)){buildRigid(n);finishModel(fit);return}
if(state.model!=='classic'){buildFlexible(n,state.model==='heart-flex');finishModel(fit);return}
// A single baked solid includes the rounded corner and horizontal through-hole.
const positions=baseTemplate.positions.slice();const extension=(n-1)*1.025/2;
for(let i=0;i<positions.length;i+=3)positions[i]+=positions[i]<0?-extension:extension;
const baseGeometry=new THREE.BufferGeometry();baseGeometry.setAttribute('position',new THREE.Float32BufferAttribute(positions,3));baseGeometry.setIndex(baseTemplate.indices);baseGeometry.computeVertexNormals();
const base=new THREE.Mesh(baseGeometry,materials.base);base.name='integrated-base';model.add(base);
for(let i=0;i<n;i++){const x=(i-(n-1)/2)*1.025;const cap=new THREE.Mesh(capGeometry,materials.keycaps);cap.userData.shared=true;cap.position.set(x,.75,0);model.add(cap);if(state.name[i]){const letter=new THREE.Mesh(glyphGeometry(state.name[i]),materials.text);letter.userData.shared=true;letter.position.set(x,1.233,0);model.add(letter)}}
// The chain passes horizontally through the reinforced upper-left corner.
const attachX=-width/2+.05,attachZ=-.54,attachY=.40;
const chain=new THREE.Group();chain.position.set(attachX,attachY,attachZ);chain.rotation.y=Math.PI/4;
for(let i=0;i<4;i++){const g=new THREE.TorusGeometry(.115,.022,6,16);g.scale(1.32,1,1);const link=new THREE.Mesh(g,materials.metal);link.rotation.x=i%2?Math.PI/2:0;link.position.set(-.20-i*.205,0,0);chain.add(link)}
const pts=[];for(let i=0;i<=96;i++){const t=i/96*Math.PI*3.85;pts.push(new THREE.Vector3(Math.cos(t)*.64,-.026+i/96*.065,Math.sin(t)*.64))}
const splitRing=new THREE.Mesh(new THREE.TubeGeometry(new THREE.CatmullRomCurve3(pts),96,.036,6,false),materials.metal);splitRing.position.set(-1.42,0,0);chain.add(splitRing);model.add(chain);
finishModel(fit)}
// Rigid variants have no articulation nodes: the whole base is one solid body.
function rigidRing(x,y){const chain=new THREE.Group();chain.position.set(x,y,0);for(let i=0;i<4;i++){const link=new THREE.Mesh(new THREE.TorusGeometry(.10,.021,6,16),materials.metal);link.scale.x=1.25;link.rotation.x=i%2?0:Math.PI/2;link.position.x=-.12-i*.18;chain.add(link)}const points=[];for(let i=0;i<=80;i++){const a=i/80*Math.PI*3.85;points.push(new THREE.Vector3(Math.cos(a)*.57,-.025+i/80*.06,Math.sin(a)*.57))}const ring=new THREE.Mesh(new THREE.TubeGeometry(new THREE.CatmullRomCurve3(points),80,.03,6,false),materials.metal);ring.position.x=-1.33;chain.add(ring);model.add(chain)}
function curvedOutline(n,spacing){const s=new THREE.Shape(),left=-(n-1)*spacing/2,r=.27,half=.56; s.moveTo(left-half+r,-half);
for(let i=0;i<n;i++){const x=left+i*spacing;s.lineTo(x+half-r,-half);s.quadraticCurveTo(x+half,-half,x+half,-half+r);if(i<n-1){const next=x+spacing-half;s.lineTo(next,-half+r);s.quadraticCurveTo(next,-half,next+r,-half)}}
const right=left+(n-1)*spacing+half;s.lineTo(right,half-r);s.quadraticCurveTo(right,half,right-r,half);
for(let i=n-1;i>=0;i--){const x=left+i*spacing;s.lineTo(x-half+r,half);s.quadraticCurveTo(x-half,half,x-half,half-r);if(i>0){const prev=x-spacing+half;s.lineTo(prev,half-r);s.quadraticCurveTo(prev,half,prev-r,half)}}s.lineTo(left-half,-half+r);s.quadraticCurveTo(left-half,-half,left-half+r,-half);s.closePath();return s}
function buildRigid(n){const wafer=state.model==='wafer',spacing=wafer?1.12:1.10,width=(n-1)*spacing+1.16,left=-(n-1)*spacing/2;modelWidth=width+3.0;
if(!materials.switch)materials.switch=material('#17191b');
if(wafer){const base=block(width,1.16,.59,.12,materials.base,.025);base.name='wafer-solid-base';model.add(base);
// A periodic diamond lattice wraps continuously around the rounded perimeter.
const positions=[],normals=[],outline=roundedShape(width,1.16,.12),perimeter=outline.getLength(),count=Math.max(8,Math.round(perimeter/.29)),step=perimeter/count;
function pointAt(u,y){const p=outline.getPointAt(((u/perimeter)%1+1)%1);return new THREE.Vector3(p.x,y,-p.y)}
for(const direction of [-1,1])for(let k=0;k<count;k++){const points=[];for(let j=0;j<=20;j++){const y=j/20*.59;points.push(pointAt(k*step+direction*y,y))}const tube=new THREE.TubeGeometry(new THREE.CatmullRomCurve3(points),20,.010,4,false),flat=tube.toNonIndexed();positions.push(...flat.attributes.position.array);normals.push(...flat.attributes.normal.array);tube.dispose();flat.dispose()}const ribs=new THREE.BufferGeometry();ribs.setAttribute('position',new THREE.Float32BufferAttribute(positions,3));ribs.setAttribute('normal',new THREE.Float32BufferAttribute(normals,3));const lattice=new THREE.Mesh(ribs,materials.base);lattice.name='continuous-wafer-lattice';model.add(lattice);
}else{const outer=curvedOutline(n,spacing),rim=outer.clone();for(let i=0;i<n;i++)rim.holes.push(new THREE.Path(roundedShape(.985,.985,.22).getPoints(8).map(p=>p.add(new THREE.Vector2(left+i*spacing,0)))));const body=new THREE.Mesh(heartExtrusion(rim,.61,0),materials.base);body.name='curved-solid-base';model.add(body);for(let i=0;i<n;i++){const floor=block(.985,.985,.13,.22,materials.base,0);floor.position.x=left+i*spacing;model.add(floor)}}
const capGeo=wafer?capGeometry:block(.94,.94,.29,.19,materials.keycaps,.035).geometry;
for(let i=0;i<n;i++){const x=left+i*spacing;if(wafer){const socket=block(.94,.94,.10,.025,materials.switch,.005);socket.position.set(x,.59,0);model.add(socket);const stem=block(.72,.72,.13,.02,materials.switch,.004);stem.position.set(x,.68,0);model.add(stem)}const cap=new THREE.Mesh(capGeo,materials.keycaps);cap.userData.shared=wafer;cap.position.set(x,wafer?.78:.57,0);model.add(cap);if(state.name[i]){const letter=sharedMesh(glyphGeometry(state.name[i]),materials.text);letter.position.set(x,wafer?1.263:.877,0);model.add(letter)}}
const eye=new THREE.Mesh(new THREE.TorusGeometry(.08,.028,6,16),materials.base);eye.position.set(-width/2-.04,.32,0);eye.rotation.y=Math.PI/2;model.add(eye);rigidRing(-width/2-.10,.32)}
function finishModel(fit){model.position.x=.75;scene.add(model);if(fit){fitDistance=getFitDistance();controls.maxDistance=Math.max(38,fitDistance*2);resetView()}invalidate()}
function heartShape(scale=1){const s=new THREE.Shape();s.moveTo(0,.36);s.bezierCurveTo(-.15,.62,-.52,.70,-.64,.33);s.bezierCurveTo(-.82,-.13,-.20,-.54,0,-.69);s.bezierCurveTo(.20,-.54,.82,-.13,.64,.33);s.bezierCurveTo(.52,.70,.15,.62,0,.36);if(scale!==1){const pts=s.getPoints(12).map(p=>p.multiplyScalar(scale));return new THREE.Shape(pts)}return s}
function heartExtrusion(shape,depth,bevel=.015){const g=new THREE.ExtrudeGeometry(shape,{depth,bevelEnabled:bevel>0,bevelSegments:2,bevelThickness:bevel,bevelSize:bevel,curveSegments:8,steps:1});g.rotateX(-Math.PI/2);return g}
function cupGeometry(outer,inner,height,floor=.10){const rim=outer.clone();rim.holes.push(new THREE.Path(inner.getPoints(24)));const walls=heartExtrusion(rim,height,0),bottom=heartExtrusion(inner,floor,0);const g=new THREE.BufferGeometry();for(const key of ['position','normal','uv']){const a=walls.attributes[key],b=bottom.attributes[key],array=new Float32Array(a.array.length+b.array.length);array.set(a.array);array.set(b.array,a.array.length);g.setAttribute(key,new THREE.BufferAttribute(array,a.itemSize))}walls.dispose();bottom.dispose();return g}
// Six circular, broad petals with recessed valleys, matching the supplied flower.
function flowerShape(scale=1){const shape=new THREE.Shape(),center=.64*scale,radius=.35*scale,half=Math.PI/6,valley=center*Math.cos(half)+Math.sqrt(radius*radius-center*center*Math.sin(half)**2),angle=Math.atan2(valley*Math.sin(half),valley*Math.cos(half)-center);for(let i=0;i<6;i++){const a=i*Math.PI/3;shape.absarc(center*Math.cos(a),center*Math.sin(a),radius,a-angle,a+angle,false)}shape.closePath();return shape}
function flowerHardware(){const tab=roundedShape(.30,.36,.14),hole=new THREE.Path();hole.absellipse(0,.035,.070,.081,0,Math.PI*2,true);tab.holes.push(hole);const lug=new THREE.Mesh(heartExtrusion(tab,.13,.008),materials.base);lug.position.set(-.37,.12,-.96);model.add(lug);const jump=new THREE.Mesh(new THREE.TorusGeometry(.115,.022,8,24),materials.metal);jump.rotation.y=Math.PI/2;jump.position.set(-.37,.225,-1.08);model.add(jump);const points=[];for(let i=0;i<=96;i++){const a=i/96*Math.PI*3.9;points.push(new THREE.Vector3(Math.cos(a)*.57,-.022+i/96*.054,Math.sin(a)*.57))}const ring=new THREE.Mesh(new THREE.TubeGeometry(new THREE.CatmullRomCurve3(points),96,.027,8,false),materials.metal);ring.position.set(-.37,.225,-1.70);model.add(ring)}
function buildDecorative(n){const flower=state.model==='flower';if(flower)n=1;else ensureHeartGeometry();const spacing=1.30,left=-(n-1)*spacing/2;modelWidth=flower?4.9:n*spacing+3;const outer=flower?flowerShape():heartShape(),inner=flower?flowerShape(.86):heartShape(.88),body=cupGeometry(outer,inner,flower?.34:.525,flower?.09:.135),cap=flower?heartExtrusion(flowerShape(.79),.155,.018):heartGeometry.cap;
for(let i=0;i<n;i++){const x=left+i*spacing,base=new THREE.Mesh(body,materials.base);base.name='rigid-decorative-base';base.position.x=x;model.add(base);const key=new THREE.Mesh(cap,materials.keycaps);key.userData.shared=!flower;key.position.set(x,flower?.285:.4625,0);model.add(key);if(state.name[i]){const text=sharedMesh(glyphGeometry(state.name[i]),materials.text);text.scale.set(flower?1.42:1.14,1,flower?1.42:1.14);text.position.set(x,flower?.457:.7145,.01);model.add(text)}if(i){const bridge=block(.28,.22,.525,.04,materials.base,0);bridge.position.set(x-spacing/2,0,0);model.add(bridge)}}
if(flower){if(!materials.flowerWell)materials.flowerWell=material('#272320');const well=new THREE.Mesh(heartExtrusion(flowerShape(.855),.009,0),materials.flowerWell);well.position.y=.10;model.add(well);flowerHardware();return}
const attach=left-.75,eye=new THREE.Mesh(new THREE.TorusGeometry(.10,.038,6,20),materials.base);eye.rotation.x=Math.PI/2;eye.position.set(attach,.27,0);model.add(eye);rigidRing(attach-.08,.27)}
function ensureHeartGeometry(){if(heartGeometry)return;const rim=heartShape();rim.holes.push(new THREE.Path(heartShape(.88).getPoints(12)));heartGeometry={cup:cupGeometry(heartShape(),heartShape(.88),.525,.135),bottom:heartExtrusion(heartShape(),.09),rim:heartExtrusion(rim,.26,.005),cap:heartExtrusion(heartShape(.855),.22,.025),joint:new THREE.TorusGeometry(.069,.023,6,16),socket:new THREE.SphereGeometry(.074,8,6)}}
function sharedMesh(g,m){const mesh=new THREE.Mesh(g,m);mesh.userData.shared=true;return mesh}
function octagonShape(size=1){const half=.60*size,cut=.18*size;return new THREE.Shape([new THREE.Vector2(-half+cut,half),new THREE.Vector2(half-cut,half),new THREE.Vector2(half,half-cut),new THREE.Vector2(half,-half+cut),new THREE.Vector2(half-cut,-half),new THREE.Vector2(-half+cut,-half),new THREE.Vector2(-half,-half+cut),new THREE.Vector2(-half,half-cut)])}
function ensureSquareGeometry(){if(squareGeometry)return;const rim=octagonShape();rim.holes.push(new THREE.Path(octagonShape(.86).getPoints()));const border=roundedShape(.79,.79,.17);border.holes.push(new THREE.Path(roundedShape(.744,.744,.148).getPoints(6)));
const eye=new THREE.Shape();eye.moveTo(-.18,-.12);eye.quadraticCurveTo(.16,-.20,.19,0);eye.quadraticCurveTo(.16,.20,-.18,.12);eye.closePath();const hole=new THREE.Path();hole.absellipse(.05,0,.083,.078,0,Math.PI*2,true,0);eye.holes.push(hole);
squareGeometry={cup:cupGeometry(octagonShape(),octagonShape(.86),.70,.12),bottom:heartExtrusion(octagonShape(),.12,.018),rim:heartExtrusion(rim,.58,.009),cap:heartExtrusion(octagonShape(.83),.25,.023),border:heartExtrusion(border,.008,.002),eye:heartExtrusion(eye,.075,.009)}}
function scallopedShape(){const outline=roundedShape(1.20,1.20,.20).getSpacedPoints(216);outline.pop();const points=outline.map((p,i)=>{const prev=outline[(i+outline.length-1)%outline.length],next=outline[(i+1)%outline.length];const tangent=next.clone().sub(prev).normalize();const depth=.014*(1+Math.cos(i/outline.length*Math.PI*2*36));return p.clone().add(new THREE.Vector2(tangent.y,-tangent.x).multiplyScalar(depth))});return new THREE.Shape(points)}
function ensureCookieGeometry(){if(cookieGeometry)return;ensureSquareGeometry();const rim=scallopedShape();rim.holes.push(new THREE.Path(roundedShape(1.025,1.025,.16).getPoints(6)));const topRim=roundedShape(.85,.85,.145);topRim.holes.push(new THREE.Path(roundedShape(.818,.818,.129).getPoints(6)));cookieGeometry={cup:cupGeometry(scallopedShape(),roundedShape(1.025,1.025,.16),.65,.10),bottom:heartExtrusion(scallopedShape(),.10,.009),rim:heartExtrusion(rim,.55,.006),well:heartExtrusion(roundedShape(1.024,1.024,.16),.015,0),cap:block(.93,.93,.28,.15,materials.keycaps,.025).geometry,topRim:heartExtrusion(topRim,.009,.003)};if(!materials.well)materials.well=material('#231d18')}
function buildFlexible(n,heart){const cookie=state.model==='cookie-flex';if(heart)ensureHeartGeometry();else if(cookie)ensureCookieGeometry();else ensureSquareGeometry();const spacing=heart?1.43:cookie?1.31:1.58,anchorY=heart?.27:cookie?.32:.35,left=-(n-1)*spacing/2;modelWidth=n*spacing+3.1;let previous;
for(let i=0;i<n;i++){const unit=new THREE.Group();unit.name='flex-character-'+i;const joint=new THREE.Group();joint.name='character-joint-'+i;
if(previous){joint.position.set(spacing/2,anchorY,0);previous.add(joint);unit.position.set(spacing/2,-anchorY,0)}else{joint.position.set(left-1.38,anchorY,0);model.add(joint);unit.position.set(1.38,-anchorY,0)}joint.add(unit);flexJoints.push(joint);joint.userData.angles={yaw:0,pitch:0};
if(heart){const body=sharedMesh(heartGeometry.cup,materials.base);body.name='heart-base-continuous';unit.add(body);const cap=sharedMesh(heartGeometry.cap,materials.keycaps);cap.position.y=.4625;unit.add(cap);if(state.name[i]){const text=sharedMesh(glyphGeometry(state.name[i]),materials.text);text.scale.set(1.14,1,1.14);text.position.set(0,.7145,.01);unit.add(text)}
for(const side of [-1,1]){if((i===0&&side===-1)||(i===n-1&&side===1))continue;const link=sharedMesh(heartGeometry.joint,materials.base);link.scale.set(1.30,1,1);link.rotation.x=side<0?Math.PI/2:0;link.position.set(side*.667,anchorY,0);unit.add(link)}
}else if(cookie){const body=sharedMesh(cookieGeometry.cup,materials.base);body.name='cookie-base-continuous';unit.add(body);const well=sharedMesh(cookieGeometry.well,materials.well);well.position.y=.605;unit.add(well);const cap=sharedMesh(cookieGeometry.cap,materials.keycaps);cap.position.y=.615;unit.add(cap);const topRim=sharedMesh(cookieGeometry.topRim,materials.keycaps);topRim.position.y=.896;unit.add(topRim);if(state.name[i]){const text=sharedMesh(glyphGeometry(state.name[i]),materials.text);text.scale.set(.91,1,.91);text.position.y=.911;unit.add(text)}for(const side of [-1,1]){if((i===0&&side===-1)||(i===n-1&&side===1))continue;const link=new THREE.Mesh(new THREE.TorusGeometry(.054,.017,6,12),materials.base);link.rotation.x=side<0?Math.PI/2:0;link.position.set(side*.638,anchorY,0);unit.add(link)}
}else{const body=sharedMesh(squareGeometry.cup,materials.base);body.name='square-base-continuous';unit.add(body);const cap=sharedMesh(squareGeometry.cap,materials.keycaps);cap.position.y=.665;unit.add(cap);const border=sharedMesh(squareGeometry.border,materials.text);border.position.y=.943;unit.add(border);if(state.name[i]){const text=sharedMesh(glyphGeometry(state.name[i]),materials.text);text.scale.set(.86,1,.86);text.position.y=.947;unit.add(text)}
for(const side of [-1,1]){if((i===0&&side===-1)||(i===n-1&&side===1))continue;const connector=sharedMesh(squareGeometry.eye,materials.base);connector.position.set(side*.70,anchorY,0);if(side<0)connector.rotation.y=Math.PI;else connector.rotation.x=Math.PI/2;unit.add(connector)}
}
flexParts.push(unit);previous=unit}
// Ring is a stationary sibling. Chain and every character swing from its attachment.
const first=flexParts[0];const eye=new THREE.Mesh(new THREE.TorusGeometry(.087,.032,6,18),materials.base);eye.rotation.x=Math.PI/2;eye.position.set(-.75,anchorY,0);first.add(eye);const chain=new THREE.Group();chain.name='moving-chain';chain.position.set(-.76,anchorY,0);for(let i=0;i<4;i++){const link=new THREE.Mesh(new THREE.TorusGeometry(.092,.020,6,16),materials.metal);link.scale.x=1.25;link.rotation.x=i%2?0:Math.PI/2;link.position.x=-.12-i*.155;chain.add(link)}first.add(chain);
const pts=[];for(let i=0;i<=80;i++){const t=i/80*Math.PI*3.85;pts.push(new THREE.Vector3(Math.cos(t)*.55,-.022+i/80*.055,Math.sin(t)*.55))}const ring=new THREE.Mesh(new THREE.TubeGeometry(new THREE.CatmullRomCurve3(pts),80,.029,6,false),materials.metal);ring.name='stationary-ring';ring.position.set(left-1.93,anchorY,0);model.add(ring);
updateSegmentOptions();applyFlex()}
function updateSegmentOptions(){const selected=$('flexCharacter').value||'all';$('flexCharacter').replaceChildren(...[[-1,'Semua karakter'],...Array.from({length:Math.max(1,state.name.length)},(_,i)=>[i,'Karakter '+(i+1)+(state.name[i]?' — '+state.name[i]: ' — kosong')])].map(([i,label])=>{const option=document.createElement('option');option.value=i<0?'all':String(i);option.textContent=label;return option}));$('flexCharacter').value=selected==='all'||Number(selected)<flexJoints.length?selected:'all'}
function applyFlex(yaw=flexAngles.yaw,pitch=flexAngles.pitch){const selected=$('flexCharacter').value||'all';flexJoints.forEach((joint,i)=>{if(selected==='all'||Number(selected)===i){const sign=selected==='all'?(i%2?-.65:1):1;joint.userData.angles={yaw:yaw*sign,pitch:pitch*sign}}const a=joint.userData.angles;joint.rotation.y=THREE.MathUtils.degToRad(a.yaw);joint.rotation.z=THREE.MathUtils.degToRad(a.pitch)});invalidate()}
function updateFlexControls(){const flexible=state.model.endsWith('-flex');$('flexSettings').hidden=!flexible;for(const id of ['flexYaw','flexPitch','flexDemo'])$(id).disabled=!flexible;$('flexHelp').textContent=state.model==='cookie-flex'?'Ombak kiri–kanan merambat antarkarakter. Ring tetap diam.':'Ombak atas–bawah merambat antarkarakter. Ring tetap diam.'}
$('flexCharacter').addEventListener('change',()=>{stopFlexDemo();const selected=$('flexCharacter').value,a=selected==='all'?{yaw:0,pitch:0}:flexJoints[Number(selected)]?.userData.angles||{yaw:0,pitch:0};flexAngles={yaw:a.yaw,pitch:a.pitch};$('flexYaw').value=a.yaw;$('flexPitch').value=a.pitch;$('yawValue').textContent=Math.round(a.yaw)+'°';$('pitchValue').textContent=Math.round(a.pitch)+'°'});
function captureWavePose(){model.updateWorldMatrix(true,true);wavePose=flexParts.map((part,i)=>{const q=flexJoints[i].getWorldQuaternion(new THREE.Quaternion());return {z:part.getWorldPosition(new THREE.Vector3()).z,y:part.getWorldPosition(new THREE.Vector3()).y,q,yaw:new THREE.Euler().setFromQuaternion(q,'YXZ').y}})}
function smoothWave(x){const v=THREE.MathUtils.clamp(x,0,1);return v*v*(3-2*v)}
function applyTravelingWave(t){const envelope=smoothWave(t/.7)*smoothWave((6-t)/.9)*(waveStopAt===null?1:smoothWave(1-(t-waveStopAt)/.7)),selected=$('flexCharacter').value||'all';
flexJoints.forEach((joint,i)=>{if(selected!=='all'&&Number(selected)!==i)return;const pose=wavePose[i];if(!pose)return;joint.updateWorldMatrix(true,false);const position=joint.getWorldPosition(new THREE.Vector3()),offset=flexParts[i].position;const phase=t*2.5-i*1.35;const rise=.13*Math.sin(phase)+.023*Math.sin(t*1.57-i*.83);const radius=Math.hypot(offset.x,offset.y);const lateral=state.model==='cookie-flex';const targetY=pose.y+(lateral?0:rise);const pitch=Math.asin(THREE.MathUtils.clamp((targetY-position.y)/radius,-.65,.65))+Math.atan2(-offset.y,offset.x);const horizontal=offset.x*Math.cos(pitch)-offset.y*Math.sin(pitch);const yaw=lateral?Math.asin(THREE.MathUtils.clamp((position.z-pose.z-rise)/horizontal,-.65,.65)):pose.yaw;const target=new THREE.Quaternion().setFromEuler(new THREE.Euler(0,yaw,pitch,'YXZ'));const world=pose.q.clone().slerp(target,envelope);const parent=joint.parent.getWorldQuaternion(new THREE.Quaternion());joint.quaternion.copy(parent.invert().multiply(world));joint.updateWorldMatrix(false,true)});invalidate()}
function stopFlexDemo(){flexDemoStart=0;waveStopAt=null;$('flexDemo').setAttribute('aria-pressed','false');$('flexDemo').textContent='Coba ombak'}
$('flexYaw').addEventListener('input',e=>{stopFlexDemo();flexAngles.yaw=Number(e.target.value);$('yawValue').textContent=flexAngles.yaw+'°';applyFlex()});$('flexPitch').addEventListener('input',e=>{stopFlexDemo();flexAngles.pitch=Number(e.target.value);$('pitchValue').textContent=flexAngles.pitch+'°';applyFlex()});
$('straighten').onclick=()=>{stopFlexDemo();$('flexCharacter').value='all';flexAngles={yaw:0,pitch:0};$('flexYaw').value=0;$('flexPitch').value=0;$('yawValue').textContent='0°';$('pitchValue').textContent='0°';applyFlex()};
$('flexDemo').onclick=()=>{if(flexDemoStart){if(waveStopAt===null)waveStopAt=(performance.now()-flexDemoStart)/1000;$('flexDemo').textContent='Menghentikan…';invalidate();return}waveStopAt=null;captureWavePose();flexDemoStart=performance.now();$('flexDemo').setAttribute('aria-pressed','true');$('flexDemo').textContent='Hentikan';invalidate()};
$('changeModel').onclick=()=>{stopFlexDemo();if(controls)controls.autoRotate=false;$('auto').setAttribute('aria-pressed','false');visible=false;stopFrames();$('editor').hidden=true;$('modelPicker').hidden=false;document.querySelector('[data-model="'+state.model+'"]').focus()};
export async function start(type){if(!['classic','heart-flex','square-flex','cookie-flex','wafer','curved','heart','flower'].includes(type))throw Error('Model tidak valid');modelColors[state.model]={base:state.base,keycaps:state.keycaps,text:state.text};state.model=type;Object.assign(state,modelColors[type]);const heart=type==='heart-flex',square=type==='square-flex',cookie=type==='cookie-flex';$('modelPicker').hidden=true;$('editor').hidden=false;visible=true;$('modelLabel').textContent=heart?'Name Clicker / Hati Fleksibel':square?'Name Clicker / Fleksibel':cookie?'Name Clicker / Fleksibel Tebal':'Name Clicker / Klasik';$('referenceTitle').textContent=heart?'Hati Fleksibel':square?'Fleksibel':cookie?'Fleksibel Tebal':'Model Klasik';$('referenceImage').src=heart?'heart-flex.jpg':square?'square-flex-side.jpg':cookie?'cookie-flex-side.jpg':'reference-side.jpg';$('referenceImage').alt=heart?'Referensi clicker hati fleksibel dengan sambungan antarkarakter':square?'Referensi bentuk samping clicker fleksibel bersudut delapan':cookie?'Referensi clicker fleksibel tebal dengan dinding base berlekuk vertikal':'Referensi profil samping model Klasik';$('referenceDescription').textContent=heart?'Hati terpisah, sambungan bergerak, dan ring perak.':square?'Base bersudut delapan, keycap berbingkai, dan sambungan bergerak.':cookie?'Base berlekuk, keycap membulat, dan sambungan fleksibel.':'Keycap kotak, huruf timbul, dan ring perak.';if(type==='wafer'||type==='curved'){const label=type==='wafer'?'Wafer':'Klasik Lengkung';$('modelLabel').textContent='Name Clicker / '+label;$('referenceTitle').textContent=label;$('referenceImage').src=type+'-card.jpg';$('referenceImage').alt='Referensi clicker '+label;$('referenceDescription').textContent=type==='wafer'?'Base berpola wafer, switch hitam, dan keycap tinggi. Tidak fleksibel.':'Base membulat menyatu, keycap kotak membulat. Tidak fleksibel.'};if(type==='heart'||type==='flower'){const label=type==='heart'?'Hati':'Bunga 1 Karakter';$('modelLabel').textContent='Name Clicker / '+label;$('referenceTitle').textContent=label;$('referenceImage').src=type+'-card.jpg';$('referenceImage').alt='Referensi '+label;$('referenceDescription').textContent=type==='heart'?'Bentuk hati dengan base menyatu dan tidak fleksibel.':'Bunga enam kelopak dengan satu karakter. Tidak fleksibel.'}$('name-help').textContent=type==='flower'?'Bunga memakai karakter pertama. Nama lengkap tetap tersimpan untuk model lainnya.':'Satu huruf, satu keycap. Huruf A–Z dan angka 0–9.';updateInfo();renderPalette();if(!ready){initializing??=init().catch(error=>{initializing=undefined;throw error});await initializing}else{buildModel(true);requestAnimationFrame(()=>{fitDistance=getFitDistance();controls.maxDistance=Math.max(38,fitDistance*2);resetView();invalidate()})}$('name').focus({preventScroll:true})}
function getFitDistance(){const aspect=camera.aspect||1;return Math.max(4.7,(modelWidth/2)/Math.tan(THREE.MathUtils.degToRad(17.5))/Math.min(aspect,1.7)*1.12)}
// Render only for a changed view; automatic rotation is capped at 30 fps.
function invalidate(){if(!ready||document.hidden||!visible||raf||rendering)return;raf=requestAnimationFrame(now=>{raf=0;if(document.hidden||!visible)return;rendering=true;if(flexDemoStart){const t=(now-flexDemoStart)/1000;if(t>=6||(waveStopAt!==null&&t>=waveStopAt+.7)){applyTravelingWave(t>=6?6:waveStopAt+.7);stopFlexDemo()}else applyTravelingWave(t)}if(controls.autoRotate)controls.update(1/30);renderer.render(scene,camera);rendering=false;if((controls.autoRotate||flexDemoStart)&&!frameTimer)frameTimer=setTimeout(()=>{frameTimer=0;invalidate()},33)})}
function stopFrames(){cancelAnimationFrame(raf);raf=0;clearTimeout(frameTimer);frameTimer=0}
document.addEventListener('visibilitychange',()=>{stopFrames();if(document.hidden){stopFlexDemo();applyFlex()}else invalidate()});
function markView(id){['perspective','top','side'].forEach(x=>$(x).classList.toggle('active',x===id))}
function resetView(){if(!ready)return;controls.target.set(-.1,.58,0);camera.position.set(fitDistance*.15,.58+fitDistance*.68,fitDistance*.78);controls.update();markView('perspective')}
function zoom(factor){if(!ready)return;camera.position.sub(controls.target).multiplyScalar(factor).add(controls.target);controls.update()}
async function init(){try{renderer=new THREE.WebGLRenderer({canvas:$('canvas'),antialias:true,alpha:true,preserveDrawingBuffer:false,powerPreference:'low-power'});renderer.setPixelRatio(Math.min(devicePixelRatio,matchMedia('(max-width: 750px)').matches?1.25:1.5));renderer.shadowMap.enabled=false;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.12;scene=new THREE.Scene();camera=new THREE.PerspectiveCamera(35,1,.05,150);controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=false;controls.minDistance=2.1;controls.maxDistance=38;controls.maxPolarAngle=Math.PI*.93;controls.enablePan=true;controls.autoRotateSpeed=1.2;controls.addEventListener('start',()=>markView(''));controls.addEventListener('change',invalidate);
scene.add(new THREE.HemisphereLight('#fffaf5','#adabb8',2.4));const light=new THREE.DirectionalLight('#fff8ee',2.3);light.position.set(-3,8,5);scene.add(light);const fill=new THREE.DirectionalLight('#edf2ff',1.1);fill.position.set(5,3,-5);scene.add(fill);
[font,baseTemplate]=await Promise.all([new FontLoader().loadAsync('./models/cooper-black.typeface.json'),fetch('./models/base-corner.json').then(r=>{if(!r.ok)throw Error('Base model unavailable');return r.json()})]);ready=true;buildModel(true);$('loading').hidden=true;const resize=()=>{const w=$('stage').clientWidth,h=$('stage').clientHeight,oldFit=fitDistance;if(!w||!h)return;renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix();fitDistance=getFitDistance();controls.maxDistance=Math.max(38,fitDistance*2);camera.position.sub(controls.target).multiplyScalar(fitDistance/oldFit).add(controls.target);controls.update();invalidate()};new ResizeObserver(resize).observe($('stage'));new IntersectionObserver(entries=>{visible=entries[0].isIntersecting&&!$('editor').hidden;stopFrames();if(visible)invalidate()},{threshold:0}).observe($('stage'));resize();invalidate();
}catch(e){$('loading').textContent='Preview 3D belum dapat dimuat. Coba muat ulang atau aktifkan akselerasi grafis di browser.';console.error(e);throw e}}
$('zoomIn').onclick=()=>zoom(.82);$('zoomOut').onclick=()=>zoom(1.22);$('reset').onclick=resetView;$('perspective').onclick=resetView;$('top').onclick=()=>{if(!ready)return;camera.position.set(-.1,.58+fitDistance,.001);controls.target.set(-.1,.58,0);controls.update();markView('top')};$('side').onclick=()=>{if(!ready)return;camera.position.set(-.1,1.02,fitDistance);controls.target.set(-.1,.63,0);controls.update();markView('side')};$('auto').onclick=()=>{if(!ready)return;controls.autoRotate=!controls.autoRotate;$('auto').setAttribute('aria-pressed',controls.autoRotate);invalidate()};
$('fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else if($('stage').requestFullscreen)await $('stage').requestFullscreen();else toast('Layar penuh tidak didukung browser ini.')}catch{toast('Layar penuh tidak tersedia.')}};
$('canvas').addEventListener('keydown',e=>{if(!ready)return;if(e.key==='+'||e.key==='='){zoom(.85);e.preventDefault()}if(e.key==='-'){zoom(1.15);e.preventDefault()}if(e.key==='Home')resetView();if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();const offset=camera.position.clone().sub(controls.target),s=new THREE.Spherical().setFromVector3(offset);if(e.key==='ArrowLeft')s.theta-=.15;if(e.key==='ArrowRight')s.theta+=.15;if(e.key==='ArrowUp')s.phi-=.15;if(e.key==='ArrowDown')s.phi+=.15;s.phi=Math.max(.04,Math.min(Math.PI*.92,s.phi));camera.position.copy(controls.target).add(new THREE.Vector3().setFromSpherical(s));controls.update()}});
$('save').onclick=()=>{if(!ready){toast('Tunggu sampai preview selesai dimuat.');return}renderer.render(scene,camera);const source=$('canvas'),out=document.createElement('canvas');out.width=1800;out.height=1300;const ctx=out.getContext('2d');const gradient=ctx.createLinearGradient(0,0,1800,1100);gradient.addColorStop(0,'#faf0e5');gradient.addColorStop(1,'#e7cfb5');ctx.fillStyle=gradient;ctx.fillRect(0,0,1800,1300);const scale=Math.min(1800/source.width,1080/source.height);ctx.drawImage(source,(1800-source.width*scale)/2,(1080-source.height*scale)/2,source.width*scale,source.height*scale);ctx.fillStyle='#fffaf5';ctx.fillRect(0,1100,1800,200);ctx.fillStyle='#332d29';ctx.font='bold 44px sans-serif';ctx.fillText(state.name||'TANPA HURUF',70,1175);ctx.font='24px sans-serif';ctx.fillText('Base: '+palette[state.base][0]+'  ·  Keycaps: '+palette[state.keycaps][0]+'  ·  Teks: '+palette[state.text][0],70,1230);out.toBlob(blob=>{if(!blob){toast('Gambar gagal disimpan. Coba lagi.');return}const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='clicker-'+state.model+'-'+(state.name||'polos')+'.png';a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);toast('Gambar desain siap diunduh.')},'image/png')};
const context=document.modelContext;if(context?.registerTool){const lifecycle=new AbortController();try{Promise.resolve(context.registerTool({name:'configure_clicker',title:'Ubah desain clicker',description:'Mengubah nama serta warna clicker dan memperbarui preview 3D.',inputSchema:{type:'object',properties:{model:{type:'string',enum:['classic','heart-flex','square-flex','cookie-flex','wafer','curved','heart','flower']},name:{type:'string',maxLength:12,pattern:'^[A-Za-z0-9]*$'},base:{type:'string',enum:palette.map(p=>p[0])},keycaps:{type:'string',enum:palette.map(p=>p[0])},text:{type:'string',enum:palette.map(p=>p[0])}},additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},async execute(input){if(!input||typeof input!=='object')throw Error('Input tidak valid');for(const k of Object.keys(input)){if(!['model','name','base','keycaps','text'].includes(k))throw Error('Properti tidak dikenal');if(k==='model'){if(!['classic','heart-flex','square-flex','cookie-flex','wafer','curved','heart','flower'].includes(input[k]))throw Error('Model tidak valid')}else if(k==='name'){if(typeof input[k]!=='string'||!/^[a-z0-9]{0,12}$/i.test(input[k]))throw Error('Nama tidak valid')}else if(!palette.some(p=>p[0]===input[k]))throw Error('Warna tidak valid')}if('model'in input)await start(input.model);for(const k of ['base','keycaps','text'])if(k in input)state[k]=palette.findIndex(p=>p[0]===input[k]);if('name'in input)setName(input.name);else{updateInfo();if(ready)updateMaterials()}renderPalette();return {model:state.model,name:state.name,base:palette[state.base][0],keycaps:palette[state.keycaps][0],text:palette[state.text][0],previewReady:ready}}},{signal:lifecycle.signal})).catch(()=>{});window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true})}catch{}}
